version: "3"
services:
  tomcat-server:
    build: .
    depends_on:
      - postgres
    ports:
      - "8383:8080"
    volumes:
      - m2_data:/root/.m2/
  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
      - 4443:443
    environment:
      PGADMIN_DEFAULT_EMAIL: igorrarruda@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    depends_on:
      - postgres
volumes:
  db_data:
  m2_data:
